# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcb7349cc54c7b2de256ba64f4166eaf6a0e690880e6fde3d4203c65c50c1476c26a7b4f2c205d39b4b17616eab005b9be9463fac891d2d699b5e5592d0ecacf

test:
  secret_key_base: ff028ed089429fc0f70060002df972f0b139b758140152d462f8c9bd1a3c55942e982035d66148275b5a77d1d29b94487a4bed4a2fd8cc7f4dd9e47c665f24a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
